### ISSUE TITLE
Error When `bower install`

### ISSUE THREAD

**Issue by CapAllen** [rawgraphs/raw#215]
```
Stack trace:
Error: connect ECONNREFUSED 69.63.184.14:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)

Console trace:
Error
    at StandardRenderer.error (/usr/lib/node_modules/bower/lib/renderers/StandardRenderer.js:88:37)
    at Logger.<anonymous> (/usr/lib/node_modules/bower/lib/bin/bower.js:113:30)
    at emitOne (events.js:116:13)
    at Logger.emit (events.js:211:7)
    at Logger.emit (/usr/lib/node_modules/bower/lib/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/lib/node_modules/bower/lib/commands/index.js:49:24
    at _rejected (/usr/lib/node_modules/bower/lib/node_modules/q/q.js:864:24)
    at /usr/lib/node_modules/bower/lib/node_modules/q/q.js:890:30
    at Promise.when (/usr/lib/node_modules/bower/lib/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/bower/lib/node_modules/q/q.js:808:41)
System info:
Bower version: 1.8.8
Node version: 8.17.0
OS: Linux 4.15.0-112-generic x64
```
And the page shows like this:
![图片](https://user-images.githubusercontent.com/35265537/91412494-73866e00-e87c-11ea-9a3e-91b1f6ddb3c8.png)

Thanks for your help.

**Comment by CapAllen** [comment]
The command is `bower install --allow-root`

**Comment by CapAllen** [comment]
It's because of the GFW, so I changed the sources of js files and solved this problem.
BTW, thanks for your awesome product!!
